### ISSUE TITLE
Initiazation of PGD attack for l1 and l2 perturbation

### ISSUE THREAD

**Issue by yljblues** [ftramer/MultiRobustness#29]
In the function 'init_delta' of *pgd_attack.py*, the perturbation is initialized uniformly at the **hypersphere** of l1 or l2 ball, instead of uniformly lying in the l1 or l2 ball.

Is it designed on purpose? Cause in this case, the initialized perturbation will always lie on the boundary of the adversarial budget.

**Comment by ftramer** [comment]
Yes that's on purpose. The way we initialise for l‐inf also gives a perturbation that lies (nearly) on the boundary of the eps‐ball if the input is high-dimensional.

We could consider other ways of sampling too. I don't expect this to make a big difference though.

**Comment by yljblues** [comment]
I see, thank you for your reply.
