### ISSUE TITLE
SLIDE inconsistent with algorithm description in paper

### ISSUE THREAD

**Issue by iamgroot42** [ftramer/MultiRobustness#5]
The normalization step of the algorithm in the paper normalizes e by its L-1 norm, whereas in the [code](https://github.com/ftramer/MultiRobustness/blob/master/pgd_attack.py#L102), it is normalized by the number of elements greater than the q-th percentile, which is not equivalent.

**Comment by ftramer** [comment]
In the algorithm in the paper, e is a signed vector so the the l1 norm counts the number of elements above the quantile

**Comment by iamgroot42** [comment]
Yes, but in the paper, the l1 norm of e_1 is used, which can be zero (if there is an equal number of positive and negative elements in the gradient). However, `num_ties` calculated in code can never be zero. These two need not be the same: I actually implemented the algorithm myself looking at the algorithm in the paper, and got NaNs several times because of this inconsistency

**Comment by ftramer** [comment]
I'm not sure I understand. The l1 norm is the sum of absolute values so it can never be zero unless the vector is zero. The l1 norm of a signed vector is exactly the same as the number of non-zero elements.

**Comment by iamgroot42** [comment]
Yes (apologies, I gave the wrong example 😅)

In case all the gradients are zero, the L1 norm of _e_, according to the paper should be 0, since all elements of e would be 0 (sign(0) = 0), which would lead to problems when implementing this (since libraries like numpy handle 0 * NaN as NaNs)

However, in the code, instead of the L1 norm, `num_ties` is being used. In this case, it would be  `tied_for_max = (abs_grad >= max_abs_grad)`, which would be all ones (since 0>=0), and we would end up dividing with a non-zero value, which would lead to no errors.

I guess when I implemented and tried this attack, this case happened for some specific inputs, because of which the loss suddenly went to NaNs

**Comment by ftramer** [comment]
Sure, if the gradient is 0 there's an inconsistency. But that's a pathological case that shouldn't typically arise when constructing adversarial examples for deep neural networks.
If you're getting zero gradients, that's maybe a sign of an issue elsewhere.

**Comment by iamgroot42** [comment]
This is just one example. Actually this problem will be there for other cases as well.
Consider grad = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2], then:

`abs_grad = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]`
The 80th percentile of this would be 0 (you can verify this by running it through numpy)

Thus, in code:
`max_abs_grad = 0`
`tied_for_max = all 1s` (since all of them are >=0)
`num_ties = 32*32*3` (for CIFAR, say)
optimal_perturbation = [1, 1, ...1] / (32*32*3)

However, according to the algorithm in the paper, we should be dividing e by its L1-norm, which would be just 2 in this case and thus the optimal perturbation would be 
`[0, 0, 0, ..., 1, 1] / 2`
I hope you see the inconsistency here.

In general, this suggests that as long as the percentile (which defaults to linear interpolation in numpy by the way, which I think is not what the intended behavior is? that's besides the point here; nearest element would also give 0 in this case) returned by numpy is 0 (for which all elements being 0 is not a necessary requirement), this problem will exist. This condition is not too hard to meet, as you can see.

**Comment by ftramer** [comment]
Yes I see. I agree that you could have gradients that are this sparse and this could cause an issue. If gradients are this sparse, simple PGD should do fine.
Again though, I don't think this should ever happen for high dimensional datasets such as mnist or cifar10 with the quantile values we considered.
